### ISSUE TITLE
Debug Kit suddenly throwing errors...

### ISSUE THREAD

**Issue by zgambino** [cakephp/debug_kit#418]
I recently updated CakePHP using composer and now on every request I'm getting the following error:
```
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[22003]: Numeric value out of range: 7 ERROR: value "1462301096" is out of range for type smallint' in /vagrant/app/vendor/cakephp/cakephp/src/Database/Statement/StatementDecorator.php:171 Stack trace: #0 /vagrant/app/vendor/cakephp/cakephp/src/Database/Statement/StatementDecorator.php(171): PDOStatement->execute(NULL) #1 /vagrant/app/vendor/cakephp/cakephp/src/Database/Statement/StatementDecorator.php(171): Cake\Database\Statement\StatementDecorator->execute(NULL) #2 /vagrant/app/vendor/cakephp/cakephp/src/Database/Log/LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL) #3 /vagrant/app/vendor/cakephp/cakephp/src/Database/Connection.php(272): Cake\Database\Log\LoggingStatement->execute() #4 /vagrant/app/vendor/cakephp/cakephp/src/Database/Query.php(188): Cake\Database\Connection->run(Object(Cake\ORM\Query)) #5 /vagrant/app/vendor/cakephp/cakephp/src/ORM/Table.php(1544): Cake\Database\Query->execute() #6 /vagrant/app/vendo in /vagrant/app/vendor/cakephp/cakephp/src/Database/Statement/StatementDecorator.php on line 171
```

After hours of troubleshooting, I discovered that the issue goes away when I disable DebugKit in my bootstrap.

I'm using CakePHP 3 and DebugKit 3.2.8.
I tried rolling back to 3.2.7, but haven't had any luck getting rid of the error. 
I can't 100% verify that this is an issue related to DebugKit, only that it goes away when I turn it off (leaving debug on).

Any ideas?

**Comment by josegonzalez** [comment]
What datasource are you using for the debugkit?

**Comment by zgambino** [comment]
Whatever the built-in one is. I'm pretty sure it's using sqlite due to the tmp file it creates.

**Comment by zgambino** [comment]
But for my main app, I'm using PostgreSQL.

**Comment by markstory** [comment]
Delete your `debug_kit.sqlite` file.
